Feature request : add cvar to disable machine gun recoil in single player #741 (baseq2)
yquake2/yquake2 pull request #747
Opened 2021-09-27 11:20 UTC by De-Seppe

This adds the cvar machinegun_norecoil
It should only impact non-deathmatch games.
I used the aimfix cvar as a template to make this change.

The cvar will only work if the game.dll supports it.

2021-09-27 16:06 UTC, Yamagi requested changes
I've added two small comments inline. Besides that it's fine and good work. :)

One small hint: Don't create pull requests from your master / main branch. All commits pushed to the branch the pull requested was created on are added to the request, you can't commit unrelated changes to master until the request was merged. And you may need to force push master for requested changes.

2021-09-27 16:06 UTC, Yamagi commented on doc/040_cvarlist.md
> +  This cvar only works if the game.dll implements this behaviour.
Can we rename the cvar to `g_machinegun_norecoil`? I know, some of the older cvars are missnamed, but we should do it right for new ones.

2021-09-27 16:06 UTC, Yamagi commented on src/game/player/weapon.c
> +
Here's one superfluous newline.

2021-09-27 16:33 UTC, De-Seppe commented
I made the necessary changes to the filename and the superfluous newline.

2021-09-28 16:36 UTC, Yamagi commented
And merged. Thank you! :) I'll add `g_machinegun_norecoil` to the list of cheat protected cvars. That's mostly a placebo but at least we can claim that we tried to prevent abuse.

2021-09-28 16:36 UTC, merged