Introduces new cvar cl_audiopaused to control if the audio loop
yquake2/yquake2 pull request #947
Opened 2022-12-11 17:24 UTC by devnexen

ought to go on or not when the game pauses.

2023-01-07 19:03 UTC, Yamagi requested changes
I have added some comments.

2023-01-07 19:03 UTC, Yamagi commented on src/client/menu/menu.c
> +    s_options_audiopause_box.generic.name = "pause sound on pause";
This overflows the menu on 320x280. And do we really want to use the last available line in the options menu for a rather obscure feature like this? I think having it as cvar only is good enough.

2023-01-07 19:03 UTC, Yamagi commented on src/client/sound/openal.c
> +	memset(&sounds, 0, sizeof(int) * MAX_EDICTS);
Why is this necessary?

2023-01-07 20:18 UTC, devnexen commented on src/client/sound/openal.c
> +	memset(&sounds, 0, sizeof(int) * MAX_EDICTS);
for matching the sdl backend mostly.

2023-01-08 09:45 UTC, Yamagi commented
Thank you :)

2023-01-08 09:45 UTC, merged